name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Configure Git for long paths
      run: |
        git config --system core.longpaths true
        
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    # 다른 steps... 